image: python:3.8

services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: misago
  POSTGRES_USER: misago
  POSTGRES_PASSWORD: misago
  REDIS_URL: redis://redis:6379/0

stages:
  - build
  - test
  - deploy

before_script:
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - python manage.py migrate
    - python manage.py collectstatic --noinput

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Deploy to your hosting service here"
